### PR TITLE
Feature/enumerables

### PR DESCRIPTION
**Pull request by YoseptF**
This is a revision on some of the methods already inside the enumerator module:
* each
* each_with_index
* select
* all?
* any?
* none?
* count?
* map
* inject
* **and** an extra one multiply_els

- [ ] In the final version, you will see a prompt asking you to enter an array (please follow the styling instructions)

image

- [ ] after that, you will select an option and the result will be shown

image

- [ ] and finally, you'll see the results

image

Remember to exit selecting the 'e' option. :grinning:

### CODE REVIEW

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

- The methods  `my_each_with_index`,` my_select` and my_map aren't working correctly, the case when there is no argument given to the method should be handled, consider using the `block_given?` method,  the rest of the methods have incorrect input, the behavior has to be exactly like the original ruby enumerable methods, please check out this [page](https://ruby-doc.org/core-2.6.5/Enumerable.html) for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by YoseptF** [comment]
Hi @Redvanisation ,
- [x] I've made the changes required to the `my_each_with_index`, `my_select` and `my_map`, I also added it to `my_each` now that I noticed it had that behavior
- [ ] Could you be more specific about  
> the rest of the methods have incorrect input

I tested again every method and they give me the right results as you can see [here](https://imgur.com/a/VbWefdJ)
the only different behavior is in the original map (the original one doesn't appear to accept a proc)
image
but that's a change asked specifically by TOP
image
Anyway, thanks for the review, and I hope you're having a great day.

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello @YoseptF   🌟

Great work Implementing the changes so far, but we still have to fix the following issues ⬇️

The below methods are behaving correctly when I check it against the original method I get the following results:

1. `my_all?`

> [1,2,3,4].my_all?(Integer)
> ArgumentError (wrong number of arguments (given 1, expected 0))


> 2.6.3 :012 > [1,2,3,4].all?(Integer)
> => true

2. `my_any?`

> 2.6.3 :012 > [1,2,3,4].my_any?(Integer)
> ArgumentError (wrong number of arguments (given 1, expected 0))
 

3. `my_none?`


> 2.6.3 :012 > [1,2,3,4].my_none?(String)
> ArgumentError (wrong number of arguments (given 1, expected 0))

4. `my_map`

Is supposed to return an Enumerator if no block is given but it is not working as intended and it is because the case when no argument is give isn't handled:

> 2.6.3 :024 > [1,2,3,4].my_map == [1,2,3,4].map
> LocalJumpError (no block given (yield))

5. `my_inject` isn't working as intended it should also give the same result as the original inject method.

Please refer to this [page](https://ruby-doc.org/core-2.6.5/Enumerable.html) for info about the original methods then fix the issues.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by YoseptF** [comment]
Hi @Redvanisation 
I've made the following corrections:
- [ ] `my_all?`, `my_any?` and `my_none?` now can handle receiving arguments
  - [ ] image
  - [ ] image
  - [ ] image
- [ ] `my_map` now returns an enumerator when called without a block
image
- [ ] `my_inject` now works as the [original one](https://ruby-doc.org/core-2.6.5/Enumerable.html#method-i-inject) (I didn't know that reference and was using the one from vscode intesisence :smiley: )
- [ ] I added the posibility to use ranges in all of the my_... methods
image


---
As always thanks for your time, and I hope you're having a wonderful day :v:

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

**Great work so far! we still have to fix the following**

1. `my_all?` when a Regex is passed as an argument it should return `true` if all of the collection matches the Regex but it returned `false`:

> 2.6.3 :037 > arr.my_all?(/d/)
>  => false 
 
> 2.6.3 :038 > arr.all?(/d/)
>  => true 


> 2.6.3 :036 > arr.my_all?(/d/) == arr.all?(/d/)
>  => false 

2. `my_any?` when a Regex is passed as an argument it should return `false` if none of the collection matches the Regex but it returned the following:

> 2.6.3 :089 > arr.my_any?(/z/)
> Traceback (most recent call last):
>        10: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/bin/irb:23:in `<main>'
>         9: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/bin/irb:23:in `load'
>         8: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
>         7: from (irb):89
>         6: from (irb):74:in `my_any?'
>         5: from (irb):31:in `my_each'
>         4: from (irb):31:in `times'
>         3: from (irb):32:in `block in my_each'
>         2: from (irb):75:in `block in my_any?'
>         1: from (irb):75:in `is_a?'
> TypeError (class or module required)

3. `my_none?` when a Regex is passed as an argument returns `true` only if none of the collection matches the Regex but instead I got the following error:

> 2.6.3 :113 > arr.my_none?(/z/)
> Traceback (most recent call last):
>        10: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/bin/irb:23:in `<main>'
>         9: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/bin/irb:23:in `load'
>         8: from /Users/redvanisation/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
>         7: from (irb):113
>         6: from (irb):98:in `my_none?'
>         5: from (irb):31:in `my_each'
>         4: from (irb):31:in `times'
>         3: from (irb):32:in `block in my_each'
>         2: from (irb):99:in `block in my_none?'
>         1: from (irb):99:in `is_a?'
> TypeError (class or module required)

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by YoseptF** [comment]
@Redvanisation 
- [ ] I think I might be doing something wrong, because when I test the method `all` (the original one) it gives me false, and it says it's the same as `my_all`
image
image
but I think it's not working the way it should, IIRC when you compare with `/d/` you are checking for digits, and everything inside `[1,2,3]` is a digit, but even on IRB and rep.lit are giving me the same result
image
image

- [ ] For the problems on `my_none` and `my_any` I had already resolved the same problem on `my_all` but I forgot to paste the solution to this two, It should be OK now :smile: 
image

**Review by uche-inyama — APPROVED** [review]
## Approved

Hi YoseptF!

Everything is working fine now!

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Pull request closed without merging**
